- id: verify-git-karma-commit-message
  name: Enforce Git Karma Commit Message convention
  description: Validate commit messages against the Karma Git commit message convention.
  entry: verify-git-karma-commit-message
  language: python
  always_run: true
  verbose: true
  types: [text]
  stages: [commit]
