name: Test with poetry

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*
      - dependabot/*
    paths-ignore:
      - "**/*.md"

jobs:
  test:
    name: Run tests
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
        poetry-version: ["1.2.2", "1.3.2", "1.4.2"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Run unit tests
        run: |
          poetry debug info
          make install
          make test
